const express = require('express');
const path = require('path');
const cors = require('cors');

function createApp({ repoRoot }) {
  const projectRoot = path.join(repoRoot, 'Projects', 'Sniper Buddy');

  // Generated by root build script via Prisma.
  // eslint-disable-next-line global-require
  const { PrismaClient } = require(path.join(projectRoot, 'generated', 'prisma', 'client'));
  const prisma = new PrismaClient();

  const app = express();
  app.use(cors());
  app.use(express.json());

  // Static assets (mounted under /p/sniper-buddy/* by the hub)
  app.use('/assets', express.static(path.join(projectRoot, 'assets')));
  app.use('/img', express.static(path.join(projectRoot, 'img')));
  app.use('/css', express.static(path.join(projectRoot, 'src', 'css')));
  app.use('/js', express.static(path.join(projectRoot, 'src', 'js')));
  app.use(express.static(path.join(projectRoot, 'src')));

  app.get('/', (req, res) => {
    res.sendFile(path.join(projectRoot, 'src', 'index.html'));
  });

  app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
  });

  app.get('/api/ballistics', async (req, res) => {
    try {
      const weapons = await prisma.weapon.findMany({
        include: {
          ammunition: {
            include: {
              ballistics: {
                orderBy: { distance: 'asc' }
              }
            }
          }
        }
      });

      const ballisticData = {};
      weapons.forEach((weapon) => {
        ballisticData[weapon.key] = {
          name: weapon.name,
          scopeMultiplier: weapon.scopeMultiplier,
          ammunition: {}
        };

        weapon.ammunition.forEach((ammo) => {
          const ballistics = {};
          ammo.ballistics.forEach((b) => {
            ballistics[b.distance.toString()] = b.mils;
          });

          ballisticData[weapon.key].ammunition[ammo.key] = {
            name: ammo.name,
            ballistics
          };
        });
      });

      res.json(ballisticData);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error('Error fetching ballistic data:', error);
      res.status(500).json({ error: 'Failed to fetch ballistic data' });
    }
  });

  // Graceful shutdown (hub process)
  process.on('SIGINT', async () => {
    await prisma.$disconnect();
  });
  process.on('SIGTERM', async () => {
    await prisma.$disconnect();
  });

  return app;
}

module.exports = { createApp };


